/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignInRouteLazyImport = createFileRoute('/sign-in')()
const AppRouteLazyImport = createFileRoute('/_app')()
const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const AppIndexLazyImport = createFileRoute('/_app/')()
const AppChatLazyImport = createFileRoute('/_app/chat')()

// Create/Update Routes

const SignInRouteLazyRoute = SignInRouteLazyImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in/route.lazy').then((d) => d.Route))

const AppRouteLazyRoute = AppRouteLazyImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/route.lazy').then((d) => d.Route))

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  path: '/',
  getParentRoute: () => SignInRouteLazyRoute,
} as any).lazy(() => import('./routes/sign-in/index.lazy').then((d) => d.Route))

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppRouteLazyRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppChatLazyRoute = AppChatLazyImport.update({
  path: '/chat',
  getParentRoute: () => AppRouteLazyRoute,
} as any).lazy(() => import('./routes/_app/chat.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatLazyImport
      parentRoute: typeof AppRouteLazyImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppRouteLazyImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof SignInRouteLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AppRouteLazyRoute: AppRouteLazyRoute.addChildren({
    AppChatLazyRoute,
    AppIndexLazyRoute,
  }),
  SignInRouteLazyRoute: SignInRouteLazyRoute.addChildren({
    SignInIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/sign-in"
      ]
    },
    "/_app": {
      "filePath": "_app/route.lazy.tsx",
      "children": [
        "/_app/chat",
        "/_app/"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in/route.lazy.tsx",
      "children": [
        "/sign-in/"
      ]
    },
    "/_app/chat": {
      "filePath": "_app/chat.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.lazy.tsx",
      "parent": "/sign-in"
    }
  }
}
ROUTE_MANIFEST_END */
