/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in/route'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as AppChatImport } from './routes/_app/chat'

// Create Virtual Routes

const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const AppIndexLazyImport = createFileRoute('/_app/')()

// Create/Update Routes

const SignInRouteRoute = SignInRouteImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in/route.lazy').then((d) => d.Route))

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/route.lazy').then((d) => d.Route))

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  path: '/',
  getParentRoute: () => SignInRouteRoute,
} as any).lazy(() => import('./routes/sign-in/index.lazy').then((d) => d.Route))

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppChatRoute = AppChatImport.update({
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() => import('./routes/_app/chat.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof SignInRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AppRouteRoute: AppRouteRoute.addChildren({ AppChatRoute, AppIndexLazyRoute }),
  SignInRouteRoute: SignInRouteRoute.addChildren({ SignInIndexLazyRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/sign-in"
      ]
    },
    "/_app": {
      "filePath": "_app/route.ts",
      "children": [
        "/_app/chat",
        "/_app/"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in/route.ts",
      "children": [
        "/sign-in/"
      ]
    },
    "/_app/chat": {
      "filePath": "_app/chat.ts",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.lazy.tsx",
      "parent": "/sign-in"
    }
  }
}
ROUTE_MANIFEST_END */
